name: 04-using-actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # checkout the code from the repository
    # following custom actions are required: install deps of our react app
    # execute automated tests
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci 
      - name: Print Folders
        run: ls -alh