name: 04-using-actions

on: workflow_dispath

jobs:
  build:
    runs-on: ubuntu-latest
    # checkout the code from the repository
    # following custom actions are required: install deps of our react app
    # execute automated tests
    steps:
      - name: Trigger event
        run: |
          echo "I was triggered by ${{ github.event_name}} event"
          echo "This job ran on $RUNNER_OS OS"
      - name: checkout code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci 
        working-directory: 04-using-actions/react-app
      - name: Print Folders
        run: ls -alh