name: My NPM workflow
on: [push, pull_request]

jobs:
  node-16-tests:
    runs-on: ubuntu-latest
    steps:
      - if: ${{github.event_name}} == "push"
        run: |
          echo "Triggered by a push event"
          echo "Runner OS: $RUNNER_OS"
          echo "Running on ${{github.ref_name}}"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - run: curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
      - run: sudo apt install nodejs
      - run: npm ci
      - run: npm test