name: My NPM workflow
on: [push, pull_request]

jobs:
  node-16-tests:
    runs-on: ubuntu-latest
    steps:
      - if: ${{github.event_name}} == "push"
        run: |
          echo "Triggered by a push event"
          echo "Runner OS: $RUNNER_OS"
          echo "Running on ${{github.ref_name}}"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: curl -fsSL https://fnm.vercel.app/install | bash
      - run: source ~/.bashrc
      - run: fnm use --install-if-missing 20
      # - run: sudo apt install nodejs
      - run: npm ci
      - run: npm test